# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: module_4/docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
    - requirements: module_4/docs/requirements.txt
```

### **2. Create `module_4/docs/requirements.txt`:**
```
sphinx-rtd-theme
sphinx-autobuild
